rsync -avh --exclude=.git/ --exclude=dvplogger/bmorse/\
      --exclude=dvplogger/moved_from_main/ --exclude=dvplogger_ext/spiffs_data_bak/ \
      --exclude=dvplogger/jk1dvplog_c/ --exclude=*.rej --exclude=dvplogger/build/ \
      --exclude=CMakeFiles/ --exclude=CMakeCache.txt --exclude=cmake_install.cmake \
      --exclude=patches/ --exclude=dvplogger_ext/moved_from_main/ --exclude=dvplogger_ext/build/ \
      --exclude=Makefile --exclude=*.o --exclude=*.a --exclude=*.elf --exclude=*.bin --exclude=*.map \
      --exclude=*.log --exclude=*~ --exclude=*.orig --exclude=dvplogger/components/arduino/cores/ \
      --exclude=dvplogger/components/arduino/docs/ --exclude=dvplogger/components/arduino/package/ \
      --exclude=dvplogger/components/arduino/tests/ --exclude=dvplogger/components/arduino/variants/ \
      --exclude=dvplogger/components/arduino/.gitignore\
      --exclude=dvplogger/components/arduino/.gitmodules\
      --exclude=dvplogger/components/arduino/.readthedocs.yaml\
      --exclude=dvplogger/components/arduino/.readthedocs.yml\
      --exclude=dvplogger/components/arduino/CMakeLists.orig.txt\
      --exclude=dvplogger/components/arduino/CMakeLists.txt\
      --exclude=dvplogger/components/arduino/CODE_OF_CONDUCT.md\
      --exclude=dvplogger/components/arduino/Kconfig.projbuild\
      --exclude=dvplogger/components/arduino/LICENSE.md\
      --exclude=dvplogger/components/arduino/README.md\
      --exclude=dvplogger/components/arduino/boards.txt\
      --exclude=dvplogger/components/arduino/idf_component.yml\
      --exclude=dvplogger/components/arduino/package.json\
      --exclude=dvplogger/components/arduino/platform.txt\
      --exclude=dvplogger/components/arduino/programmers.txt\
      --exclude=.github/ --exclude=dvplogger/components/arduino/tools/ \
      --exclude='*.old' --exclude='.gitignore' \
      --exclude='*_old.cpp' \
      --exclude='dvplogger.tar.gz'\
      --exclude='archive_source.sh'\
      --exclude='README.md'\
      --exclude='*.lock'\
      --exclude='.git_backup/' \
      --exclude='LICENSE' \
      --exclude='.github/' \
      /home/araki/esp/dvplogger-devel/ /home/araki/esp/dvplogger/
